# Generated by Django 2.0.5 on 2018-05-30 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('telefone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^(\\d+)$')], verbose_name='Telefone')),
                ('mensagem', models.TextField()),
            ],
        ),
    ]
